### ISSUE TITLE
Cannot access /srv

### ISSUE THREAD

**Issue by merlinlcb** [ccarney16/pterodactyl-docker#62]
following your most recent instructions for installation i get to where i am to add my core.json file, but there is no way for me to access /srv/daemon as there is no shared environment for that folder please advise of a solution at your earliest convenience

**Comment by ccarney16** [comment]
Uh, I am a bit confused. If you are going the route of manually adding in the file, you need to create `/srv/daemon/config/`. Otherwise you can run the configuration tool for the daemon by running `docker-compose run --rm daemon <cmd>`, where cmd is the command generated by pterodactyl's auto configure.
